name: Cloudflare Pages build and deployment

on:
  push:
    branches:
      # Don't forget to set correct production branch:
      # https://developers.cloudflare.com/pages/configuration/branch-build-controls/#production-branch-control
      - '*'

  # manual trigger
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  job-1:
    name: Build and deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the Application
        run: pnpm run build-only

      # Note: there cannot be top level 404.html or SPA rendering won't work because Cloudflare pages will look for non-existing .html files
      # https://developers.cloudflare.com/pages/configuration/serving-pages/#single-page-application-spa-rendering
      - name: Upload build to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          # Get the credentials here:
          # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#get-credentials-from-cloudflare
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: new-movues
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
